### ISSUE TITLE
How to test after I upgrade to Rxjava2 which is using Disposable rather than Subscription to execute user case

### ISSUE THREAD

**Issue by TonyTangAndroid** [jordifierro/android-base#1]
After having spent half a month comparing different Android Application Architecture with the support of test, this repository demonstrates  the best example of possible modern architecture. 

So I made modifications based on this code base to make it fully support Parse.com, which you could find the code in this branch : [https://github.com/TonyTangAndroid/android-base/tree/parse](parse).

Since Rxjava2 has been published, so I plan to make a further update to make it support Rxjava2. And I indeed make it except a big issue : now the use case is not testable because Rxjava2 is using `Disposable` rather than `Subscription` to execute user case.

To make myself better understood, please refer to the following link which compares the current implementation of `Usecase.java` with the previous one.

[use_case_comparison_screen_shot](https://raw.githubusercontent.com/TonyTangAndroid/android-base/parse_rxjava2_without_test/screenshot/use_case_comparison.png)

You could checkout my branch [parse_rxjava2_without_test](https://github.com/TonyTangAndroid/android-base/tree/parse_rxjava2_without_test) to see more details.

I have been stuck on this problem for 3 days. Any help or suggestion will be greatly appreciated.

**Comment by jordifierro** [comment]
Hi @TonyTangAndroid! 

Thanks for your comment, I really appreciate it and I'm glad that you found my repo useful.

I haven't used RxJava 2 yet and I don't know which is exactly the problem that you describe, but I'll try to update the project libraries (on the next days) and solve the problem you comment.

**Comment by TonyTangAndroid** [comment]
Thank you very much for getting back to me and trying to make an effort to help me. Feel free to let me know if I could be of assistance.

**Comment by jordifierro** [comment]
Hi again @TonyTangAndroid! 

I think I have a good solution for the problem you explained. I have created a pull request to show and discuss it with you before it's completely finished (it's almost done, but I have no more time to work on it until next week :( ).

Here is the pull request -> #2

**Comment by TonyTangAndroid** [comment]
Hi @jordifierro I am astonished that you really had finished all necessary code change to use Rxjava2. And by comparing all the necessary changes that you have done, I am truly feeling the power of clean architecture, which is easy to maintain. Based on my limited understanding of rxjava2, I had added one comment about using Completable rather Observable when the expected result is void. I also raised another potential issue over there in regard to deleting note issue. Please let me know if I failed in making myself understood. Again, thank you very much for your quick and awesome response and have a super happy holiday.

**Comment by jordifierro** [comment]
Hi again @TonyTangAndroid! I've just merged the #2 pull request to the `master` branch, I hope the modifications can help you with your project. Thanks for asking and for your help, I really appreciate it! Any other question or suggestion you have, don't hesitate to open another issue or pull request.
