### ISSUE TITLE
onSaveInstanceState method is not implemented

### ISSUE THREAD

**Issue by kamadi** [jordifierro/android-base#9]
What is the best way of implementing `onSaveInstanceState `?
1) Creating another entities in data module and implement `Parcelable ` interface in this classes.
2) Saving state of presenters

**Comment by jordifierro** [comment]
Hi @kamadi! First of all thanks for asking, all issues are welcome :)

The Android way of doing this is saving data on `onSaveInstanceState` and restore it later. Nevertheless, I think that making fragment or activity responsible of storing data absolutely breaks the clean approach.

My favourite solution is to equip the data repositories with caches and fetch the data each time the view is created/recreated. Thus, we have quick responses when the screen is rotated and we also keep the responsibilities in place, which will benefit our code in multiple aspects.

If that's too much for your project or the approach doesn't convince you, I would choose the answer 2: saving state of presenters. Actually, saving the entire presenter itself. Cache them with a reference or any other method you like and avoid their destruction. That will avoid repeating the data fetching process and it won't burden the presentation layer with storage issues.

Hope it helps. Tell me if you try any solution and how it works!
